language: minimal

dist: bionic

# sudo: false
sudo: required

#addons:
  #apt:
    #packages:
      #- python-pygments
      #- ghostscript

## Uncomment the following lines if you use minted package or custom fonts
before_install:
 #- mkdir $HOME/.debpkgs
 - mkdir $HOME/.fonts
 - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
 - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.debpkgs

# Change working directory so including files will work

before_script:
  - echo "Print content of $HOME/.debpkgs"
  - ls $HOME/.debpkgs
  - echo "Check whether apt-get has no cache"
  - ls /var/cache/apt/archives
  -
  - echo "Start loading cache"
  - |
    exist() {
        [ -e "$1" ]
    }
  - |
    if exist ~/$HOME/.debpkgs/*.deb
    then
        sudo mv ~/$HOME/.debpkgs/*.deb /var/cache/apt/archives/
        ls /var/cache/apt/archives
    fi
  -
  - echo "Start to install software"
  - sudo apt-get install -y --no-install-recommends --no-install-suggests python-pygments ghostscript
  - echo "Start updating the cache"
  - cp /var/cache/apt/archives/*deb ~/$HOME/.debpkgs/
  - cd $TRAVIS_BUILD_DIR/src/

#before_script: cd $TRAVIS_BUILD_DIR/src/
script:
  # Texliveonfly will download packages automatically
  #- texliveonfly main.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  #- latexmk -pdf main.tex
  #- texliveonfly biber-mwe.tex
  #- texliveonfly fonts.tex --compiler=lualatex
  - texliveonfly --arguments='-shell-escape' minted.tex

  # But you could use any other compiler as well instead of latexmk. Example:
#  - pdflatex main.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex
