language: generic

stages:
  - name: latex
    if: commit_message !~ mint and commit_message !~ font and commit_message !~ full and commit_message !~ skip-ci and commit_message !~ ci-skip 
  - name: minted 
    if: commit_message =~ mint and commit_message !~ font and commit_message !~ full and commit_message !~ skip-ci and commit_message !~ ci-skip 
  - name: fonts
    if: commit_message =~ font and commit_message !~ mint and commit_message !~ full and commit_message !~ skip-ci and commit_message !~ ci-skip 
  - name: full
    if: commit_message =~ full and commit_message !~ mint and commit_message !~ font and commit_message !~ skip-ci and commit_message !~ ci-skip
  
cache:
  directories:
    - /tmp/texlive

jobs:
  include:
    - stage: latex
      install: source ./texlive/texlive_install.sh
      script: texlua mybuild.lua
    - stage: minted
      before_install: 
      - sudo apt-get install python-pygments
      install: source ./texlive/texlive_install.sh
      script: texlua mybuild.lua
    - stage: fonts
      before_install:
      - mkdir $HOME/.fonts
      - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
      - fc-cache -f -v
      install: source ./texlive/texlive_install.sh
      script: texlua mybuild.lua
    - stage: full
      before_install:
      - sudo apt-get install python-pygments
      - mkdir $HOME/.fonts
      - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
      - fc-cache -f -v
      install: source ./texlive/texlive_install.sh
      script: texlua mybuild.lua

notifications:
  email: true
