r"""
This file was *autogenerated* from main.tex with sagetex.sty
version 2015/08/26 v3.0-92d9f7a. It contains the contents of all the
sageexample environments from main.tex. You should be able to
doctest this file with "sage -t main_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 70::

        sage: r,B = var('r,B')
        sage: f = (x*r*B)/((1-x)^2 * (1-x*r))
        sage: f.partial_fraction(x)
    

"""
